export const browserCoreExamples = [
  "MrBeanBot browser status",
  "MrBeanBot browser start",
  "MrBeanBot browser stop",
  "MrBeanBot browser tabs",
  "MrBeanBot browser open https://example.com",
  "MrBeanBot browser focus abcd1234",
  "MrBeanBot browser close abcd1234",
  "MrBeanBot browser screenshot",
  "MrBeanBot browser screenshot --full-page",
  "MrBeanBot browser screenshot --ref 12",
  "MrBeanBot browser snapshot",
  "MrBeanBot browser snapshot --format aria --limit 200",
  "MrBeanBot browser snapshot --efficient",
  "MrBeanBot browser snapshot --labels",
];

export const browserActionExamples = [
  "MrBeanBot browser navigate https://example.com",
  "MrBeanBot browser resize 1280 720",
  "MrBeanBot browser click 12 --double",
  'MrBeanBot browser type 23 "hello" --submit',
  "MrBeanBot browser press Enter",
  "MrBeanBot browser hover 44",
  "MrBeanBot browser drag 10 11",
  "MrBeanBot browser select 9 OptionA OptionB",
  "MrBeanBot browser upload /tmp/file.pdf",
  'MrBeanBot browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "MrBeanBot browser dialog --accept",
  'MrBeanBot browser wait --text "Done"',
  "MrBeanBot browser evaluate --fn '(el) => el.textContent' --ref 7",
  "MrBeanBot browser console --level error",
  "MrBeanBot browser pdf",
];
